### PR TITLE
Added VTK file output support

### PR DESCRIPTION
**Pull request by peytondmurray**
I've always liked using [Paraview][paraview] for viewing micromagnetic simulations, so I added two new input file commands which allow for spins to be written in VTK file format:

* `config:vtk` works the same way as `config:atoms`, and enables the spins to be written to files formatted according to the VTK file spec.
* `config:vtk-output-rate` changes the rate at which the files are written, as a multiple of `sim:time-steps-increment`.

@richard-evans, I noticed that the `develop` branch is far behind `master` - is `master` still the right branch to submit this pull request to?

[paraview]: https://www.paraview.org

### CODE REVIEW

**Comment by peytondmurray** [comment]
I'll take a look - it shouldn't be an issue to switch over. It looks like `develop` has moved away from using the .sln and instead favors the makefile now - is this correct? Are you still building on Windows at all?

**Comment by richard-evans** [comment]
Ahh! The develop branch also has rudimentary cuda support :D. Anyway, I have no experience of cmake but certainly open to using it if it makes compilation easier.

**Comment by peytondmurray** [comment]
I don't have any experience with CMake either, but I'm willing to take a look to see if it will work. I was hoping to work a little bit on the CUDA code later on, so preserving that functionality is important.

**Comment by richard-evans** [comment]
Ok thanks - if you can get a build working with Cmake that would be good! I got a bit fed up of manually importing the files into VS every time I changed something, and so if there is an automatic way of doing that it would be very good.

**Comment by richard-evans** [comment]
Thanks Payton. I have now added support for new format vtk files from the new vdc utility.

**Pull request closed without merging**
