### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by am1808**
Corrected bug in Slonczewski field calculation

### CODE REVIEW

**Comment by am1808** [comment]
Fixed incorrect definition of the function "integrate_mpi" in sr/simulate/sim.cpp

**Comment by richard-evans** [comment]
OK - if you can make the changes I'll accept the pull request, thanks Andrea!

**Comment by am1808** [comment]
I am actually not familiar with vmath::iround(). Does it convert long integers as well? Otherswise I think it is probably better to switch to **cmath::lround()**.

**Comment by richard-evans** [comment]
around() is in the vmath.hpp header file `inline int iround( double value ){
		return static_cast<int>(floor( value + 0.5 ));
	}` - we just need to define a int64_t version of the same. In general I prefer overloaded functions for things that are the same.

**Pull request merged**
